---
content: |
  # Base Arch Install 12345
  
  ## Prepare LCD
  
  ```zsh
  # Add Remote Server
  lxc remote add paddi 10.172.31.254:8843
  # Set Remote to be Deafult
  lxc remote set-default paddi
  # Create OVS Switch
  lxc network create ovsbr0 bridge.driver=openvswitch
  ```
  
  ## Install Base Image from the Internet
  
  ```zsh
  lxc image copy --alias=arch  images:archlinux paddi:
  # or
  lxc image copy images:archlinux local: --alias arch-remote --auto-update
  lxc init arch name.goes.here
  lxc start name.goes.here
  
  ```
  
  ## Install Base Image from local tarball
  
  ---
  
  ## Configure Base Arch Image
  
  ### Add zsh config files
  
  ```zsh
  
  pacman -Sy --needed --noconfirm
  pacman --needed --noconfirm -S base-devel
  pacman --needed --noconfirm -S zsh bridge-utils psmisc vim git tree rsync bc wget tmux lsof
  pacman --needed --noconfirm -S ctags sudo python perl btrfs-progs ebtables
  pacman --needed --noconfirm -S cmake
  
  git clone --recurse-submodules --recursive --config http.sslVerify=false https://bitbucket.org/pSox/psoxizsh.git /etc/psoxizsh
  cd /etc/psoxizsh
  git checkout develop
  cd
  cat <<ZSHRC >/etc/skel/.zshrc
  
  export TERM=xterm-256color
  
  # Added by psoxizsh
  grep -qE . ~/.psoxizsh/zshrc 2>>/dev/null && source ~/.psoxizsh/zshrc || source /etc/psoxizsh/zshrc
  
  ZSHRC
  cp -v /etc/skel/.zshrc  ~
  useradd -D -s /bin/zsh
  useradd -D
  chsh -s /bin/zsh
  install -v --mode=700 -d ~/.ssh
  install -v --mode=700 -d /etc/skel/.ssh
  su -
  
  ```
  
  If you seed the new zsh prompt then logout and log back in.
  
  ### Install vim plugins
  
  ```zsh
  vim -c PlugInstall -c qa
  
  ```
  
  ### Add pacman User
  
  ```zsh
  useradd -u 9696 -m -G wheel -d /usr/local/pacman -s /usr/bin/zsh pacman
  cat <<SUDO >/etc/sudoers.d/50_pacman
  pacman ALL=(ALL) NOPASSWD: ALL
  SUDO
  chmod 600 /etc/sudoers.d/50_pacman
  ```
  
  ### Add custom User
  
  ```zsh
  (
  export USER_NAME=pstemmet
  useradd \
    -m \
    -G wheel,users \
    -s /usr/bin/zsh \
    -p '$6$eJCeHI42MBP60yVF$yisIsRVGkscfLZi93pdCAMRFtCY5TSzjvyAWPlibx3gwypqkIjTM7E9MFNOr8QASxkfQ6AvnUwFDLZ.VqWpIE' \
    ${USER_NAME}
  cat <<SUDO >/etc/sudoers.d/50_${USER_NAME}
  ${USER_NAME} ALL=(ALL) NOPASSWD: ALL
  SUDO
  chmod 600 /etc/sudoers.d/50_${USER_NAME}
  )
  
  ```
  
  ### Add and Configure Package Managers
  
  ```zsh
  sudo -iupacman mkdir -vp .cache/yay/yay-bin
  curl https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=yay-bin | sudo -iupacman tee .cache/yay/yay-bin/PKGBUILD
  sudo -iupacman zsh -c "cd .cache/yay/yay-bin; makepkg"
  pacman -U ~pacman/.cache/yay/yay-bin/yay-bin*.pkg.tar.xz --noconfirm
  sudo -iupacman yay -S yaourt --noconfirm --needed
  
  ```
  
  ## LXD Config
  
  ### Install LXD
  
  ```zsh
  yay -S --needed --noconfirm lxd
  systemctl enable lxd.socket
  systemctl start  lxd.socket
  
  ```
  
  ### Configure LXD
  
  ```zsh
  sed -i -E 's|^#?Domains=.*|Domains=lxpad.int|' /etc/systemd/resolved.conf
  systemctl restart systemd-resolved.service
  hostnamectl set-hostname $(hostname -s).lxpad.int
  
  sysctl -w net.ipv6.conf.all.disable_ipv6=1
  cat <<NO_IPV6  >/etc/sysctl.d/10-no-ipv6.conf
  net.ipv6.conf.all.disable_ipv6 = 1
  NO_IPV6
  sed -i -E "s/(^[0-9.]+\s+$(hostname -s).*)/# DON'T TOUCH : \1/" /etc/hosts
  lxd init
  
  ```
  
  ### Update Default Profile
  
  * Add the following to the default profile using the `lxc profile edit default` command.
  
  * Do not modify the `name:` and `used_by:` tags.
  
  ```yaml
  config:
    boot.autostart: "true"
    linux.kernel_modules: bridge,br_netfilter,ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,ebtable_broute,openvswitch
    raw.lxc: |-
      lxc.apparmor.profile=unconfined
      lxc.cgroup.devices.allow = a
      lxc.mount.auto=proc:rw sys:rw
      lxc.cap.drop =
    security.nesting: "true"
    security.privileged: "true"
  devices:
    mem:
      path: /dev/mem
      type: unix-char
    root:
      path: /
      pool: paddi-store
      type: disk
  ```
  
  ### LXD OpenVSwitch Config
  
  ```zsh
  # lxc network create ovs01 bridge.driver=openvswitch
  # lxc network create ovs00 bridge.driver=openvswitch ipv4.address="172.30.33.254/23" ipv4.nat=true ipv6.address="fd00:cafe:1::ffff/64" ipv6.nat=true
  ```
  
  ### LXD 3.0.0 Renamed Configs
  
  | Legacy Key               | New Key                       | Comments |
  | ------------------------ | ----------------------------- | -------- |
  | lxc.aa_profile           | lxc.apparmor.profile          |
  | lxc.aa_allow_incomplete  | lxc.apparmor.allow_incomplete |
  | lxc.console              | lxc.console.path              |
  | lxc.devttydir            | lxc.tty.dir                   |
  | lxc.haltsignal           | lxc.signal.halt               |
  | lxc.id_map               | lxc.idmap                     |
  | lxc.init_cmd             | lxc.init.cmd                  |
  | lxc.init_gid             | lxc.init.gid                  |
  | lxc.init_uid             | lxc.init.uid                  |
  | lxc.kmsg                 | -                             | removed  |
  | lxc.limit                | lxc.prlimit                   |
  | lxc.logfile              | lxc.log.file                  |
  | lxc.loglevel             | lxc.log.level                 |
  | lxc.mount                | lxc.mount.fstab               |
  | lxc.network              | lxc.net                       |
  | lxc.network.             | lxc.net.[i].                  |
  | lxc.network.flags        | lxc.net.[i].flags             |
  | lxc.network.hwaddr       | lxc.net.[i].hwaddr            |
  | lxc.network.ipv4         | lxc.net.[i].ipv4.address      |
  | lxc.network.ipv4.gateway | lxc.net.[i].ipv4.gateway      |
  | lxc.network.ipv6         | lxc.net.[i].ipv6.address      |
  | lxc.network.ipv6.gateway | lxc.net.[i].ipv6.gateway      |
  | lxc.network.link         | lxc.net.[i].link              |
  | lxc.network.macvlan.mode | lxc.net.[i].macvlan.mode      |
  | lxc.network.mtu          | lxc.net.[i].mtu               |
  | lxc.network.name         | lxc.net.[i].name              |
  | lxc.network.script.down  | lxc.net.[i].script.down       |
  | lxc.network.script.up    | lxc.net.[i].script.up         |
  | lxc.network.type         | lxc.net.[i].type              |
  | lxc.network.veth.pair    | lxc.net.[i].veth.pair         |
  | lxc.network.vlan.id      | lxc.net.[i].vlan.id           |
  | lxc.pivotdir             | -                             | removed  |
  | lxc.pts                  | lxc.pty.max                   |
  | lxc.rebootsignal         | lxc.signal.reboot             |
  | lxc.rootfs               | lxc.rootfs.path               |
  | lxc.se_context           | lxc.selinux.context           |
  | lxc.seccomp              | lxc.seccomp.profile           |
  | lxc.stopsignal           | lxc.signal.stop               |
  | lxc.syslog               | lxc.log.syslog                |
  | lxc.tty                  | lxc.tty.max                   |
  | lxc.utsname              | lxc.uts.name                  |
  
...
