[tasks.npm]
command = "npm"
args = ["run-script", "prod"]

[tasks.run]
env = { "ROCKET_ADDRESS" = "172.17.17.223", "ROCKET_PORT" = "8001" }
command = "cargo"
args = ["run"]

[tasks.init]
dependencies = [
    "npm",
    "run"
]